AWSTemplateFormatVersion: '2010-09-09'
Description: 'Healthcare data lake - core resources'

Parameters:
  BucketName:
    Description: Bucket for ingesting and processing healthcare data
    Type: String
  ArtifactBucketName:
    Description: Bucket for holding software artifacts
    Type: String

Resources:
  #-------------------------------------------------------------- Data Lake bucket
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption: # Encryption at rest
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration: # Block all public access
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactBucketName
      BucketEncryption: # Encryption at rest
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration: # Block all public access
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  #-------------------------------------------------------------- API Gateway
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub ${AWS::StackName}-APIGateway
      ProtocolType: HTTP

  DefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties: 
      ApiId: !Ref HttpApi
      AutoDeploy: true
      Description: Default stage
      StageName: $default
  
  #-------------------------------------------------------------- Communication topic (use attributes to determine filtering)
  Topic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: !Sub ${AWS::StackName}-Topic
      KmsMasterKeyId: alias/aws/sns # Using default key for now
      
Outputs:
  Bucket:
    Value: !Ref Bucket
    Export:
      Name: !Sub ${AWS::StackName}-Bucket
  ArtifactBucket:
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub ${AWS::StackName}-ArtifactBucket
  HttpApi:
    Value: !Ref HttpApi
    Export:
      Name: !Sub ${AWS::StackName}-HttpApi
  HttpApiArn:
    Value: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}
    Export:
      Name: !Sub ${AWS::StackName}-HttpApiArn
  Topic:
    Value: !Ref Topic
    Export:
      Name: !Sub ${AWS::StackName}-Topic