AWSTemplateFormatVersion: '2010-09-09'
Description: 'Healthcare data lake - core resources'

Parameters:
  BucketName:
    Description: Bucket for ingesting and processing healthcare data
    Type: String
  ArtifactBucketName:
    Description: Bucket for holding software artifacts
    Type: String

Resources:
  #-------------------------------------------------------------- Data Lake bucket
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption: # Encryption at rest
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration: # Block all public access
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action: 's3:*' # Only allow secure transport
          Effect: Deny
          Principal: '*'
          Resource:
          - !Sub arn:aws:s3:::${Bucket}
          - !Sub arn:aws:s3:::${Bucket}/*
          Condition:
            Bool: 
              'aws:SecureTransport': false
            
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactBucketName
      BucketEncryption: # Encryption at rest
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration: # Block all public access
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  ArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref ArtifactBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action: 's3:*' # Only allow secure transport
          Effect: Deny
          Principal: '*'
          Resource:
          - !Sub arn:aws:s3:::${ArtifactBucket}
          - !Sub arn:aws:s3:::${ArtifactBucket}/*
          Condition:
            Bool: 
              'aws:SecureTransport': false
  #-------------------------------------------------------------- Catalog to go with the data lake buckets
  Catalog:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
      - AttributeName: "message_id"
        AttributeType: "S"
      KeySchema: 
      - AttributeName: "message_id"
        KeyType: "HASH"
      TableName: !Sub ${AWS::StackName}-Catalog
      BillingMode: PAY_PER_REQUEST
  
  #-------------------------------------------------------------- Communication / hub topic (use attributes to determine filtering)
  Topic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: !Sub ${AWS::StackName}-Topic
      DisplayName: "Pub-Sub-Hub"
      KmsMasterKeyId: alias/aws/sns # Using default key

Outputs:
  Bucket:
    Value: !Ref Bucket
    Export:
      Name: !Sub ${AWS::StackName}-Bucket
  ArtifactBucket:
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub ${AWS::StackName}-ArtifactBucket
  Topic:
    Value: !Ref Topic
    Export:
      Name: !Sub ${AWS::StackName}-Topic
  Catalog:
    Value: !Ref Catalog
    Export:
      Name: !Sub ${AWS::StackName}-Catalog
  CatalogArn:
    Value: !GetAtt Catalog.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CatalogArn